apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: springboot-azure-ci-pipeline-template
  title: Spring Boot With Azure CI pipeline
  description: Create a simple Java SpringBoot Application With Azure CI Pipeline
  tags:
  - java
  - springboot
  - cicd
spec:
  owner: group:catalog-admin
  type: service

  parameters:
  - title: Provide some simple information
    required:
    - name
    - java_package_name
    - java_group_id
    - java_artifact_id
    - sonarProjectKey
    - checkmarxProjectName
    - blackduckProjectName
    properties:
      name:
        title: Name
        type: string
        description: Unique name of the component
        ui:field: EntityNamePicker
      java_package_name:
        title: Java Package Name
        type: string
        description: Name for the java package. eg (io.backstage.blah)
      java_group_id:
        title: Java Group ID
        type: string
        description: Name for the java app Group ID. eg (io.backstage.blah)
      java_artifact_id:
        title: Java Artifact ID
        type: string
        description: Name for the java app Artifact ID. eg (io.backstage.blah)
        ui:field: ValidationField
        ui:options:
          regex: "^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$"
          errorMessage: Must start and end with a letter or number, and can contain letters, numbers, hyphens, and dots in between.Maximum length is 50 characters.
      description:
        title: Description
        type: string
        description: Help others understand what this website is for.
      sonarProjectKey:
        title: Project Key of Sonarqube
        type: string
        description: Name of the Sonarqube Project Key
        ui:autofocus: true
      checkmarxProjectName:
        title: Project Name of Checkmarx
        type: string
        description: Name of the Project for Checkmarx Scan
        ui:autofocus: true
      blackduckProjectName:
        title: Project Name of Blackduck
        type: string
        description: Name of the Project for Blackduck Scan
        ui:autofocus: true
  - title: Choose a location
    required:
    - repoUrl
    properties:
      repoUrl:
        title: Repository Location
        type: string
        ui:field: RepoUrlPicker
        ui:options:
          allowedHosts:
          - dev.azure.com

  steps:
  - id: template
    name: Fetch Skeleton + Template
    action: fetch:template
    input:
      url: ./skeleton
      values:
        name: ${{ parameters.name }}
        description: ${{ parameters.description }}
        artifact_id: ${{ parameters.java_artifact_id }}
        group_id: ${{ parameters.java_group_id }}
        java_package_name: ${{ parameters.java_package_name }}
        java_package_name_slash: ${{ parameters.java_package_name.replaceAll('.', '/') }}
        branchName: ${{ parameters.branchName }}
        sonarProjectKey: ${{ parameters.sonarProjectKey }}
        checkmarxProjectName: ${{ parameters.checkmarxProjectName }}
        blackduckProjectName: ${{ parameters.blackduckProjectName }}
        destination: ${{ parameters.repoUrl | parseRepoUrl }}
        http_port: 8080

  - id: publish

    name: Publish
    action: publish:azure
    input:
      allowedHosts: ["dev.azure.com"]
      description: This is ${{ parameters.name }}
      repoUrl: ${{ parameters.repoUrl }}

  - id: register
    name: Register
    action: catalog:register
    input:
      repoContentsUrl: https://dev.azure.com/${{ (parameters.repoUrl | parseRepoUrl).organization }}/${{ (parameters.repoUrl | parseRepoUrl).project }}/_git/${{ (parameters.repoUrl | parseRepoUrl).repo }}
      catalogInfoPath: "/catalog-info.yaml"

  - id: apply-pipeline
    name: Create Azure Pipeline
    action: azure:pipeline:create
    input: 
      organization: ${{ (parameters.repoUrl | parseRepoUrl)['organization'] }}
      project: ${{ (parameters.repoUrl | parseRepoUrl)['project'] }}
      repositoryName: ${{ (parameters.repoUrl | parseRepoUrl)['repo'] }}
      repoType: 'TfsGit'
      branchName: 'master'
      serviceConnectionName: ''

  output:
    links:
    - title: Repository
      url: https://dev.azure.com/${{ (parameters.repoUrl | parseRepoUrl).organization }}/${{ (parameters.repoUrl | parseRepoUrl).project }}/_git/${{ (parameters.repoUrl | parseRepoUrl).repo }}
    - title: Open in catalog
      icon: catalog

      entityRef: ${{ steps.register.output.entityRef }}
