apiVersion: v1
data:
  oauth2-proxy.cfg: |-
    provider="azure"
    oidc_issuer_url="https://login.microsoftonline.com/TENANT_ID/v2.0"
    cookie_secure=true
    scope="openid email"
    http_address="0.0.0.0:4180"
    upstreams=["INGRESS_BASE_URL"]
    redirect_url = "INGRESS_BASE_URL/oauth2/callback"
    email_domains=["*"]
    whitelist_domains=["INGRESS_DNS:*"]
    set_xauthrequest=false
    skip_auth_strip_headers=false
    set_authorization_header=true
    pass_authorization_header=true
    pass_basic_auth=true
    pass_user_headers=true
    pass_host_header=true
kind: ConfigMap
metadata:
  name: oauth2-proxy-config
  namespace: oauth2-proxy
