serviceAccount: $SERVICE_ACCOUNT_EMAIL
logsBucket: ${{values.gcp_logs_bucket}}

substitutions:
  _REPO_SHORT: ${REPO_NAME:0:63}
  _IMAGE_NAME: ${_REPO_SHORT,,}
  _RUN_SONARSCAN: 'true'
  _SONAR_WAIT_FOR_QUALITY_GATE: 'true'

steps:
- name: 'node'
  entrypoint: 'yarn'
  args: ['install']

- name: 'node'
  entrypoint: 'yarn'
  args: ['build']

- name: 'node'
  entrypoint: 'yarn'
  args: ['test']

- name: 'debian'
  entrypoint: 'bash'
  id: 'Install and Run SonarQube Scanner'
  args:
    - '-c'
    - |
      echo "Installing required utilities..."
      apt-get update && apt-get install -y wget unzip curl
      echo "Installing Node.js v20.x"
      curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
      apt-get install -y nodejs
      echo "Verifying Node.js installation..."
      node -v
      echo "Installing SonarQube scanner..."
      wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-6.2.1.4610-linux-x64.zip
      unzip sonar-scanner-cli-6.2.1.4610-linux-x64.zip
      mv sonar-scanner-6.2.1.4610-linux-x64 /opt/sonar-scanner
      /opt/sonar-scanner/bin/sonar-scanner -v

      if [[ "${_RUN_SONARSCAN}" == "true" ]]; then
        echo "...........* RUNNING SONARQUBE SCAN *.........."
        /opt/sonar-scanner/bin/sonar-scanner \
          -Dsonar.projectKey="${{values.sonarProjectKey}}" \
          -Dsonar.sources=. \
          -Dsonar.exclusions="node_modules/**,cicd/**,coverage/**,out/**,jest.config.js,jest.setup.js,next.config.mjs" \
          -Dsonar.host.url=$$SonarUrl \
          -Dsonar.login=$$SonarToken \
          -Dsonar.coverage.jacoco.xmlReportPaths=./coverage/jacoco.xml \
          -Dsonar.javascript.lcov.reportPaths=./coverage/lcov.info \
          -Dsonar.qualitygate.wait=${_SONAR_WAIT_FOR_QUALITY_GATE}

        if [ $? -ne 0 ]; then
          echo "SonarQube scan failed."
          echo 1 > build_status.txt
          exit 1
        else
          echo "SonarQube scan passed."
          echo 0 > build_status.txt
        fi
      else
        echo "...........* SKIPPING SONARQUBE SCAN *.........."
        echo 0 > build_status.txt
      fi
  secretEnv: ['SonarToken','SonarUrl']
- name: 'debian'
  entrypoint: 'bash'
  id: 'Scan Next.js project inside a specific directory'
  args:
    - '-c'
    - |
      apt-get update && apt-get install -y curl unzip openjdk-17-jdk
      mkdir -p /usr/local/bin/checkmarx-cli
      curl -o /usr/local/bin/checkmarx-cli/cxconsoleplugin.zip -L https://download.checkmarx.com/9.5.0/Plugins/CxConsolePlugin-1.1.30.zip
      unzip /usr/local/bin/checkmarx-cli/cxconsoleplugin.zip -d /usr/local/bin/checkmarx-cli/
      chmod +x /usr/local/bin/checkmarx-cli/runCxConsole.sh
      sourceLocation=$(pwd)
      /usr/local/bin/checkmarx-cli/runCxConsole.sh Scan -v \
        -CxServer "$$SCANURL" \
        -CxUser "$$SCANUSER" \
        -CxPassword "$$SCANPASS" \
        -ProjectName "$$SCANTEAM\\${{values.checkmarxProjectName}}" \
        -LocationType "folder" \
        -LocationPath "$sourceLocation/" \
        -preset "Cognizant Default Preset" \
        -ReportPDF "$sourceLocation/${{values.checkmarxProjectName}}.pdf"
  secretEnv: ['SCANURL','SCANPASS','SCANUSER','SCANTEAM']

- name: 'debian'
  entrypoint: 'bash'
  id: 'BDH Scan Next.js project'
  args:
    - '-c'
    - |
      apt-get update && apt-get install -y curl unzip openjdk-17-jdk
      curl -s -L "$${BDHDETECTURL}" | bash -s -- \
          --blackduck.url=$$BDHURL \
          --blackduck.api.token=$$BDHTOKEN \
          --detect.project.name="${{values.blackduckProjectName}}" \
          --detect.project.version.name="ver.1" \
          --blackduck.trust.cert=true \
          --detect.timeout=3600 \
          --detect.detector.search.depth=0 \
          --detect.tools=ALL,IAC_SCAN \
          --detect.blackduck.signature.scanner.individual.file.matching=ALL \
          --detect.accuracy.required=NONE \
          --detect.detector.search.continue=true \
          --logging.level.com.synopsys.integration=DEBUG \
          --detect.risk.report.pdf=true \
          --detect.risk.report.pdf.path="report" \
          --detect.blackduck.signature.scanner.snippet.matching=SNIPPET_MATCHING \
          --detect.excluded.directories=.git
  secretEnv: ['BDHDETECTURL', 'BDHURL', 'BDHTOKEN']

- name: 'Create Repository In Artifact'
  id: 'create-repo'
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      if ! gcloud artifacts repositories list --location=${{values.gcp_location}} | grep -q ${{values.gcp_artifact_registry_repo_name}}; then
        gcloud artifacts repositories create ${{values.gcp_artifact_registry_repo_name}} --repository-format=docker --location=${{values.gcp_location}} --description="My Docker repository"
      fi

- name: 'Build Docker Image and Push Docker image to Artifact Registry'
  id: 'build-images'
  name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      docker build -t ${{values.gcp_location}}-docker.pkg.dev/$PROJECT_ID/${{values.gcp_artifact_registry_repo_name}}/${_IMAGE_NAME}:$COMMIT_SHA .
      docker tag ${{values.gcp_location}}-docker.pkg.dev/$PROJECT_ID/${{values.gcp_artifact_registry_repo_name}}/${_IMAGE_NAME}:$COMMIT_SHA ${{values.gcp_location}}-docker.pkg.dev/$PROJECT_ID/${{values.gcp_artifact_registry_repo_name}}/${_IMAGE_NAME}:latest
      docker push ${{values.gcp_location}}-docker.pkg.dev/$PROJECT_ID/${{values.gcp_artifact_registry_repo_name}}/${_IMAGE_NAME}:latest
      docker push ${{values.gcp_location}}-docker.pkg.dev/$PROJECT_ID/${{values.gcp_artifact_registry_repo_name}}/${_IMAGE_NAME}:$COMMIT_SHA

availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/CheckmarxUrl/versions/1
    env: SCANURL
  - versionName: projects/$PROJECT_ID/secrets/CheckmarxPassword/versions/1
    env: SCANPASS
  - versionName: projects/$PROJECT_ID/secrets/CheckmarxUsername/versions/1
    env: SCANUSER
  - versionName: projects/$PROJECT_ID/secrets/CheckmarxTeam/versions/1
    env: SCANTEAM
  - versionName: projects/$PROJECT_ID/secrets/SonarToken/versions/1
    env: SonarToken
  - versionName: projects/$PROJECT_ID/secrets/SonarUrl/versions/1
    env: SonarUrl
  - versionName: projects/$PROJECT_ID/secrets/BLACKDUCKDETECTURL/versions/1
    env: BDHDETECTURL
  - versionName: projects/$PROJECT_ID/secrets/BLACKDUCKURL/versions/1
    env: BDHURL
  - versionName: projects/$PROJECT_ID/secrets/BLACKDUCKTOKEN/versions/1
    env: BDHTOKEN