apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: microfrontend-shell-app-with-nextjs-template-aws 
  title: Microfrontend Shell App with NextJs for AWS
  description: Create a new Microfrontend Shell app using NextJs and Typescript.
  tags:
    - nextjs
    - typescript
    - ci
    - aws
spec:
  owner: group:catalog-admin
  type: website
  parameters:
    - title: Provide some simple information
      required:
        - name
        - owner
        - aws_code_region
        - default_branch
        - sonarProjectKey
        - checkmarxProjectName
        - blackduckProjectName
        - namespace
        - appName
      properties:
        name:
          title: Name
          type: string
          description: Unique name of the component
          ui:field: EntityNamePicker
        aws_code_region:
          title: AWS Region
          type: string
          description: AWS region in which repository should be created. eg (us-east-1)
        default_branch:
          title: Branch Name
          type: string
          description: Branch name for the repository. eg('main' or 'master')  
        description:
          title: Description
          type: string
          description: Help others understand what this project is for.
        sonarProjectKey:
          title: Project Key of Sonarqube
          type: string
          description: Name of the Sonarqube Project Key
          ui:autofocus: true
        checkmarxProjectName:
          title: Project Name of Checkmarx
          type: string
          description: Name of the Project for Checkmarx Scan
          ui:autofocus: true
        blackduckProjectName:
          title: Project Name of Blackduck
          type: string
          description: Name of the Project for Blackduck Scan
          ui:autofocus: true
        namespace:
          title: Namespace
          description: Name of the namespace used in Kubernetes deployment
          type: string
        appName:
          title: App Name
          description: App name used to set the Kubernetes label selector
          type: string
        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group
    - title: Choose a location
      required:
        - repoUrl
        - collaborators
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
        collaborators:
          title: GitHub Team Collaborators
          type: string
          description: Name of the GitHub team to add as collaborators
          ui:autofocus: true
  steps:
    - id: template
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./skeleton
        copyWithoutRender:
          - .github/workflows/*
        values:
          name: ${{ parameters.name }}
          description: ${{ parameters.description }}
          destination: ${{ parameters.repoUrl | parseRepoUrl }}
          owner: ${{ parameters.owner }}
          default_branch: ${{ parameters.default_branch }}
          aws_code_region: ${{ parameters.aws_code_region }}
          repo_name: ${{ (parameters.repoUrl | parseRepoUrl).repo }}
          pipelineName: ${{ (parameters.repoUrl | parseRepoUrl).repo }}-ci-pipeline
          projectName: ${{ (parameters.repoUrl | parseRepoUrl).repo }}-build-project
          sonarProjectKey: ${{ parameters.sonarProjectKey }}
          checkmarxProjectName: ${{ parameters.checkmarxProjectName }}
          blackduckProjectName: ${{ parameters.blackduckProjectName }}
          namespace: ${{ parameters.namespace }}
          appName: ${{ parameters.appName }}


    - id: publish
      name: Publish
      action: publish:github
      input:
        allowedHosts: ["github.com"]
        description: This is ${{ parameters.component_id }}
        repoUrl: ${{ parameters.repoUrl }}
        defaultBranch: ${{ parameters.default_branch }}
        collaborators:
          - team: ${{ parameters.owner }}/${{ parameters.collaborators }}
            access: push
        protectDefaultBranch: false


    - id: apply-pipeline
      name: Create Aws Pipeline
      action: aws:pipeline:create-v1
      input:
        pipelineName: ${{ (parameters.repoUrl | parseRepoUrl).repo }}-ci-pipeline
        projectName: ${{ (parameters.repoUrl | parseRepoUrl).repo }}-build-project
        repositoryName: ${{ (parameters.repoUrl | parseRepoUrl).repo }}
        branchName: ${{ parameters.default_branch }}
        githubOwner: ${{ (parameters.repoUrl | parseRepoUrl).owner }}
        buildSpec: buildspec-build.yml
        
    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: "/catalog-info.yaml"

  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
