apiVersion: v1
data:
  OAUTH2_PROXY_CLIENT_ID: 
  OAUTH2_PROXY_CLIENT_SECRET: 
  OAUTH2_PROXY_COOKIE_SECRET: 
kind: Secret
metadata:
  name: oauth2-proxy-secrets
  namespace: oauth2-proxy
type: Opaque
