# General 
project_id = "cog01hy0xaqm3kfh4mr4t3em9ex2m"
region     = "us-east1"

# Private Pool
private_pool_name = "flowsource-private-pool"

# Network
source_network_name                  = "flowsource-vpc"
peering_network_name                 = "flowsource-private-pool-peering-vpc"
source_vpn_gateway_name              = "flowsource-vpc-vpn-gw"
peering_vpn_gateway_name             = "flowsource-private-pool-peering-vpc-vpn-gw"
source_router_name                   = "flowsource-vpc-vpn-router"
peering_router_name                  = "flowsource-private-pool-peering-vpc-vpn-router"
source_tunnel1                       = "tunnel-peering-flowsource-vpc-if0"
source_tunnel2                       = "tunnel-peering-flowsource-vpc-if1"
peering_tunnel1                      = "tunnel-flowsource-private-pool-peering-vpc-if0"
peering_tunnel2                      = "tunnel-flowsource-private-pool-peering-vpc-if1"
source_vpn_router_interface1         = "flowsource-vpc-vpn-router-interface1"
source_router_interface_ip_address1  = "169.254.0.1/30"
source_router_peer1                  = "flowsource-vpc-vpn-router-peer1"
source_router_peer_ip_address1       = "169.254.0.2"
source_vpn_router_interface2         = "flowsource-vpc-vpn-router-interface2"
source_router_interface_ip_address2  = "169.254.1.2/30"
source_router_peer2                  = "flowsource-vpc-vpn-router-peer2"
source_router_peer_ip_address2       = "169.254.1.1"
peering_vpn_router_interface1        = "flowsource-private-pool-peering-vpc-vpn-router-interface1"
peering_router_interface_ip_address1 = "169.254.0.2/30"
peering_router_peer1                 = "flowsource-private-pool-peering-vpc-vpn-router-peer1"
peering_router_peer_ip_address1      = "169.254.0.1"
peering_vpn_router_interface2        = "flowsource-private-pool-peering-vpc-vpn-router-interface2"
peering_router_interface_ip_address2 = "169.254.1.1/30"
peering_router_peer2                 = "flowsource-private-pool-peering-vpc-vpn-router-peer2"
peering_router_peer_ip_address2      = "169.254.1.2"