global:
  replicaCount: 1
  namespace: flowsource

  authuiConfig:
    AUTH_DOMAIN: "<AsShownInIdentityProvider>"
    DISPLAY_MODE: "optionFirst"
    SELECT_TENANT_UI_TITLE: "Flowsource Auth UI"
    LOGO: ""
    STYLE_URL: ""
    TENANTS_DISPLAY_NAME: "Flowsource Auth UI"
    TENANTS_ICON_URL: "https://www.gstatic.com/firebasejs/ui/2.0.0/images/auth/anonymous.png"
    TENANTS_LOGO_URL: ""
    TENANTS_BUTTON_COLOR: "#007bff"
    TENANTS_IMMEDIATE_FEDERATED_REDIRECT: true
    TENANTS_SIGN_IN_FLOW: "redirect"
    TENANTS_SIGN_IN_OPTIONS_PROVIDER: "microsoft.com"

  authui:
    service:
      type: ClusterIP
      annotations: |
        cloud.google.com/neg: '{"exposed_ports": {"80":{}}}'
    secret:
      gcpProjectId: "123456789"

  serviceAccount:
    name: default # Use the Kubernetes Service Account Name which impersonates Service Account 3 mentioned in roles.md if other than default KSA is being used for workload identity ex: flowsource-gke-ksa